# Generated by Django 3.0.5 on 2021-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('loc_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30, unique=True)),
                ('planet', models.CharField(max_length=30, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='spaceship',
            fields=[
                ('ship_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('model', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('planet', models.CharField(max_length=30)),
                ('status', models.CharField(
                    choices=[('decommissioned', 'decommissioned'), ('maintenance', 'maintenance '),
                             ('operational', 'operational')], default=None, max_length=30)),
            ],
        ),
    ]
